$folder="X:\DDC";             # Directory to place the new folders in.
$root0 = "Class_000___Computer_science_information_and_general_works";
$root1 = "Class_100___Philosophy_and_psychology";
$root2 = "Class_200___Religion";
$root3 = "Class_300___Social_sciences";
$root4 = "Class_400___Language";
$root5 = "Class_500___Science";
$root6 = "Class_600___Technology";
$root7 = "Class_700___Arts_and_recreation";
$root8 = "Class_800___Literature";
$root9 = "Class_900___History_and_geography";

new-item -type directory -path $folder\$root0\000_Computer_science_knowledge_and_systems
new-item -type directory -path $folder\$root0\000_Computer_science_information_and_general_works
new-item -type directory -path $folder\$root0\001_Knowledge
new-item -type directory -path $folder\$root0\002_The_book_writing_libraries_and_book_related_topics
new-item -type directory -path $folder\$root0\003_Systems
new-item -type directory -path $folder\$root0\004_Data_processing_and_computer_science
new-item -type directory -path $folder\$root0\005_Computer_programming_programs_and_data
new-item -type directory -path $folder\$root0\006_Special_computer_methods_eg_AI_multimedia_VR4
new-item -type directory -path $folder\$root0\007_009_Unassigned
new-item -type directory -path $folder\$root0\010_Bibliographies
new-item -type directory -path $folder\$root0\010_Bibliography
new-item -type directory -path $folder\$root0\011_Bibliographies
new-item -type directory -path $folder\$root0\012_Bibliographies_of_individuals
new-item -type directory -path $folder\$root0\013_Unassigned
new-item -type directory -path $folder\$root0\014_Bibliographies_of_anonymous_and_pseudonymous_works
new-item -type directory -path $folder\$root0\015_Bibliographies_of_works_from_specific_places
new-item -type directory -path $folder\$root0\016_Bibliographies_of_works_on_specific_subjects
new-item -type directory -path $folder\$root0\017_General_subject_catalogs
new-item -type directory -path $folder\$root0\018_Catalogs_arranged_by_author_date_etc
new-item -type directory -path $folder\$root0\019_Dictionary_catalogs
new-item -type directory -path $folder\$root0\020_Library_and_information_sciences
new-item -type directory -path $folder\$root0\021_Library_relationships_with_archives_information_centers_etc
new-item -type directory -path $folder\$root0\022_Administration_of_physical_plant
new-item -type directory -path $folder\$root0\023_Personnel_management
new-item -type directory -path $folder\$root0\024_Unassigned
new-item -type directory -path $folder\$root0\025_Library_operations
new-item -type directory -path $folder\$root0\026_Libraries_for_specific_subjects
new-item -type directory -path $folder\$root0\027_General_libraries
new-item -type directory -path $folder\$root0\028_Reading_and_use_of_other_information_media
new-item -type directory -path $folder\$root0\029_Unassigned
new-item -type directory -path $folder\$root0\030_Encyclopedias_and_books_of_facts
new-item -type directory -path $folder\$root0\030_General_encyclopedic_works
new-item -type directory -path $folder\$root0\031_Encyclopedias_in_American_English
new-item -type directory -path $folder\$root0\032_Encyclopedias_in_English
new-item -type directory -path $folder\$root0\033_Encyclopedias_in_other_Germanic_languages
new-item -type directory -path $folder\$root0\034_Encyclopedias_in_French_Occitan_and_Catalan
new-item -type directory -path $folder\$root0\035_Encyclopedias_in_Italian_Romanian_and_related_languages
new-item -type directory -path $folder\$root0\036_Encyclopedias_in_Spanish_and_Portuguese
new-item -type directory -path $folder\$root0\037_Encyclopedias_in_Slavic_languages
new-item -type directory -path $folder\$root0\038_Encyclopedias_in_Scandinavian_languages
new-item -type directory -path $folder\$root0\039_Encyclopedias_in_other_languages
new-item -type directory -path $folder\$root0\040_Unassigned_formerly_Biographies
new-item -type directory -path $folder\$root0\050_Magazines_journals_and_serials
new-item -type directory -path $folder\$root0\050_General_serial_publications
new-item -type directory -path $folder\$root0\051_Serials_in_American_English
new-item -type directory -path $folder\$root0\052_Serials_in_English
new-item -type directory -path $folder\$root0\053_Serials_in_other_Germanic_languages
new-item -type directory -path $folder\$root0\054_Serials_in_French_Occitan_and_Catalan
new-item -type directory -path $folder\$root0\055_Serials_in_Italian_Romanian_and_related_languages
new-item -type directory -path $folder\$root0\056_Serials_in_Spanish_and_Portuguese
new-item -type directory -path $folder\$root0\057_Serials_in_Slavic_languages
new-item -type directory -path $folder\$root0\058_Serials_in_Scandinavian_languages
new-item -type directory -path $folder\$root0\059_Serials_in_other_languages
new-item -type directory -path $folder\$root0\060_Associations_organizations_and_museums
new-item -type directory -path $folder\$root0\060_General_organizations_and_museum_science
new-item -type directory -path $folder\$root0\061_Organizations_in_North_America
new-item -type directory -path $folder\$root0\062_Organizations_in_British_Isles_in_England
new-item -type directory -path $folder\$root0\063_Organizations_in_central_Europe_in_Germany
new-item -type directory -path $folder\$root0\064_Organizations_in_France_and_Monaco
new-item -type directory -path $folder\$root0\065_Organizations_in_Italy_and_adjacent_islands
new-item -type directory -path $folder\$root0\066_Organizations_in_Iberian_peninsula_and_adjacent_islands
new-item -type directory -path $folder\$root0\067_Organizations_in_eastern_Europe_in_Russia
new-item -type directory -path $folder\$root0\068_Organizations_in_other_geographic_areas
new-item -type directory -path $folder\$root0\069_Museum_science
new-item -type directory -path $folder\$root0\070_News_media_journalism_and_publishing
new-item -type directory -path $folder\$root0\071_Newspapers_in_North_America
new-item -type directory -path $folder\$root0\072_Newspapers_in_British_Isles_in_England
new-item -type directory -path $folder\$root0\073_Newspapers_in_central_Europe_in_Germany
new-item -type directory -path $folder\$root0\074_Newspapers_in_France_and_Monaco
new-item -type directory -path $folder\$root0\075_Newspapers_in_Italy_and_adjacent_islands
new-item -type directory -path $folder\$root0\076_Newspapers_in_Iberian_peninsula_and_adjacent_islands
new-item -type directory -path $folder\$root0\077_Newspapers_in_eastern_Europe_in_Russia
new-item -type directory -path $folder\$root0\078_Newspapers_in_Scandinavia
new-item -type directory -path $folder\$root0\079_Newspapers_in_other_geographic_areas
new-item -type directory -path $folder\$root0\080_Quotations
new-item -type directory -path $folder\$root0\080_General_collections
new-item -type directory -path $folder\$root0\081_Collections_in_American_English
new-item -type directory -path $folder\$root0\082_Collections_in_English
new-item -type directory -path $folder\$root0\083_Collections_in_other_Germanic_languages
new-item -type directory -path $folder\$root0\084_Collections_in_French_Occitan_Catalan
new-item -type directory -path $folder\$root0\085_Collections_in_Italian_Romanian_and_related_languages
new-item -type directory -path $folder\$root0\086_Collections_in_Spanish_and_Portuguese
new-item -type directory -path $folder\$root0\087_Collections_in_Slavic_languages
new-item -type directory -path $folder\$root0\088_Collections_in_Scandinavian_languages
new-item -type directory -path $folder\$root0\089_Collections_in_other_languages
new-item -type directory -path $folder\$root0\090_Manuscripts_and_rare_books
new-item -type directory -path $folder\$root0\091_Manuscripts
new-item -type directory -path $folder\$root0\092_Block_books
new-item -type directory -path $folder\$root0\093_Incunabula
new-item -type directory -path $folder\$root0\094_Printed_books
new-item -type directory -path $folder\$root0\095_Books_notable_for_bindings
new-item -type directory -path $folder\$root0\096_Books_notable_for_illustrations
new-item -type directory -path $folder\$root0\097_Books_notable_for_ownership_or_origin
new-item -type directory -path $folder\$root0\098_Prohibited_works_forgeries_and_hoaxes
new-item -type directory -path $folder\$root0\099_Books_notable_for_format
new-item -type directory -path $folder\$root1\100_Philosophy
new-item -type directory -path $folder\$root1\100_Philosophy_and_psychology
new-item -type directory -path $folder\$root1\101_Theory_of_philosophy
new-item -type directory -path $folder\$root1\102_Miscellany
new-item -type directory -path $folder\$root1\103_Dictionaries_and_encyclopedias
new-item -type directory -path $folder\$root1\104_No_longer_used___formerly_Essays
new-item -type directory -path $folder\$root1\105_Serial_publications
new-item -type directory -path $folder\$root1\106_Organizations_and_management
new-item -type directory -path $folder\$root1\107_Education_research_related_topics_of_philosophy
new-item -type directory -path $folder\$root1\108_Groups_of_people
new-item -type directory -path $folder\$root1\109_History_and_collected_biography
new-item -type directory -path $folder\$root1\110_Metaphysics
new-item -type directory -path $folder\$root1\111_Ontology
new-item -type directory -path $folder\$root1\112_No_longer_used___formerly_Methodology
new-item -type directory -path $folder\$root1\113_Cosmology_Philosophy_of_nature
new-item -type directory -path $folder\$root1\114_Space
new-item -type directory -path $folder\$root1\115_Time
new-item -type directory -path $folder\$root1\116_Change
new-item -type directory -path $folder\$root1\117_Structure
new-item -type directory -path $folder\$root1\118_Force_and_energy
new-item -type directory -path $folder\$root1\119_Number_and_quantity
new-item -type directory -path $folder\$root1\120_Epistemology
new-item -type directory -path $folder\$root1\120_Epistemology_causation_and_humankind
new-item -type directory -path $folder\$root1\121_Epistemology_Theory_of_knowledge
new-item -type directory -path $folder\$root1\122_Causation
new-item -type directory -path $folder\$root1\123_Determinism_and_indeterminism
new-item -type directory -path $folder\$root1\124_Teleology
new-item -type directory -path $folder\$root1\125_No_longer_used___formerly_Infinity
new-item -type directory -path $folder\$root1\126_The_self
new-item -type directory -path $folder\$root1\127_The_unconscious_and_the_subconscious
new-item -type directory -path $folder\$root1\128_Humankind
new-item -type directory -path $folder\$root1\129_Origin_and_destiny_of_individual_souls
new-item -type directory -path $folder\$root1\130_Parapsychology_and_occultism
new-item -type directory -path $folder\$root1\131_Parapsychological_and_occult_methods_for_achieving_well_being_happiness_success
new-item -type directory -path $folder\$root1\132_No_longer_used___formerly_Mental_derangements
new-item -type directory -path $folder\$root1\133_Specific_topics_in_parapsychology_and_occultism
new-item -type directory -path $folder\$root1\134_No_longer_used___formerly_Mesmerism_and_Clairvoyance
new-item -type directory -path $folder\$root1\135_Dreams_and_mysteries
new-item -type directory -path $folder\$root1\136_No_longer_used___formerly_Mental_characteristics
new-item -type directory -path $folder\$root1\137_Divinatory_graphology
new-item -type directory -path $folder\$root1\138_Physiognomy
new-item -type directory -path $folder\$root1\139_Phrenology
new-item -type directory -path $folder\$root1\140_Philosophical_schools_of_thought
new-item -type directory -path $folder\$root1\140_Specific_philosophical_schools_and_viewpoints
new-item -type directory -path $folder\$root1\141_Idealism_and_related_systems_and_doctrines
new-item -type directory -path $folder\$root1\142_Critical_philosophy
new-item -type directory -path $folder\$root1\143_Bergsonism_and_intuitionism
new-item -type directory -path $folder\$root1\144_Humanism_and_related_systems_and_doctrines
new-item -type directory -path $folder\$root1\145_Sensationalism
new-item -type directory -path $folder\$root1\146_Naturalism_and_related_systems_and_doctrines
new-item -type directory -path $folder\$root1\147_Pantheism_and_related_systems_and_doctrines
new-item -type directory -path $folder\$root1\148_Dogmatism_eclecticism_liberalism_syncretism_and_traditionalism
new-item -type directory -path $folder\$root1\149_Other_philosophical_systems_and_doctrines
new-item -type directory -path $folder\$root1\150_Psychology
new-item -type directory -path $folder\$root1\151_No_longer_used___formerly_Intellect
new-item -type directory -path $folder\$root1\152_Sensory_perception_movement_emotions_and_physiological_drives
new-item -type directory -path $folder\$root1\153_Conscious_mental_processes_and_intelligence
new-item -type directory -path $folder\$root1\154_Subconscious_and_altered_states_and_processes
new-item -type directory -path $folder\$root1\155_Differential_and_developmental_psychology
new-item -type directory -path $folder\$root1\156_Comparative_psychology
new-item -type directory -path $folder\$root1\157_No_longer_used___formerly_Emotions
new-item -type directory -path $folder\$root1\158_Applied_psychology
new-item -type directory -path $folder\$root1\159_No_longer_used___formerly_Will
new-item -type directory -path $folder\$root1\160_Philosophical_logic
new-item -type directory -path $folder\$root1\161_Induction
new-item -type directory -path $folder\$root1\162_Deduction
new-item -type directory -path $folder\$root1\163_164_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root1\165_Fallacies_and_sources_of_error
new-item -type directory -path $folder\$root1\166_Syllogisms
new-item -type directory -path $folder\$root1\167_Hypotheses
new-item -type directory -path $folder\$root1\168_Argument_and_persuasion
new-item -type directory -path $folder\$root1\169_Analogy
new-item -type directory -path $folder\$root1\170_Ethics
new-item -type directory -path $folder\$root1\170_Ethics_Moral_philosophy
new-item -type directory -path $folder\$root1\171_Ethical_systems
new-item -type directory -path $folder\$root1\172_Political_ethics
new-item -type directory -path $folder\$root1\173_Ethics_of_family_relationships
new-item -type directory -path $folder\$root1\174_Occupational_ethics
new-item -type directory -path $folder\$root1\175_Ethics_of_recreation_leisure_public_performances_communication
new-item -type directory -path $folder\$root1\176_Ethics_of_sex_and_reproduction
new-item -type directory -path $folder\$root1\177_Ethics_of_social_relations
new-item -type directory -path $folder\$root1\178_Ethics_of_consumption
new-item -type directory -path $folder\$root1\179_Other_ethical_norms
new-item -type directory -path $folder\$root1\180_Ancient_medieval_and_Eastern_philosophy
new-item -type directory -path $folder\$root1\180_Ancient_medieval_eastern_philosophy
new-item -type directory -path $folder\$root1\181_Eastern_philosophy
new-item -type directory -path $folder\$root1\182_Pre_Socratic_Greek_philosophies
new-item -type directory -path $folder\$root1\183_Sophistic_Socratic_related_Greek_philosophies
new-item -type directory -path $folder\$root1\184_Platonic_philosophy
new-item -type directory -path $folder\$root1\185_Aristotelian_philosophy
new-item -type directory -path $folder\$root1\186_Skeptic_and_Neoplatonic_philosophies
new-item -type directory -path $folder\$root1\187_Epicurean_philosophy
new-item -type directory -path $folder\$root1\188_Stoic_philosophy
new-item -type directory -path $folder\$root1\189_Medieval_Western_philosophy
new-item -type directory -path $folder\$root1\190_Modern_Western_philosophy_19th_century_20th_century
new-item -type directory -path $folder\$root1\190_Modern_Western_and_other_noneastern_philosophy
new-item -type directory -path $folder\$root1\191_Philosophy_of_the_United_States_and_Canada
new-item -type directory -path $folder\$root1\192_Philosophy_of_the_British_Isles
new-item -type directory -path $folder\$root1\193_Philosophy_of_Germany_and_Austria
new-item -type directory -path $folder\$root1\194_Philosophy_of_France
new-item -type directory -path $folder\$root1\195_Philosophy_of_Italy
new-item -type directory -path $folder\$root1\196_Philosophy_of_Spain_and_Portugal
new-item -type directory -path $folder\$root1\197_Philosophy_of_Russia
new-item -type directory -path $folder\$root1\198_Philosophy_of_Scandinavia_and_Finland
new-item -type directory -path $folder\$root1\199_Philosophy_in_other_geographic_areas
new-item -type directory -path $folder\$root2\200_Religion
new-item -type directory -path $folder\$root2\201_Religious_mythology_general_classes_of_religion_interreligious_relations_and_attitudes_social_theology
new-item -type directory -path $folder\$root2\202_Doctrines
new-item -type directory -path $folder\$root2\203_Public_worship_and_other_practices
new-item -type directory -path $folder\$root2\204_Religious_experience_life_practice
new-item -type directory -path $folder\$root2\205_Religious_ethics
new-item -type directory -path $folder\$root2\206_Leaders_and_organization
new-item -type directory -path $folder\$root2\207_Missions_and_religious_education
new-item -type directory -path $folder\$root2\208_Sources
new-item -type directory -path $folder\$root2\209_Sects_and_reform_movements
new-item -type directory -path $folder\$root2\210_Philosophy_and_theory_of_religion
new-item -type directory -path $folder\$root2\211_Concepts_of_God
new-item -type directory -path $folder\$root2\212_Existence_ways_of_knowing_God_attributes_of_God
new-item -type directory -path $folder\$root2\213_Creation
new-item -type directory -path $folder\$root2\214_Theodicy
new-item -type directory -path $folder\$root2\215_Science_and_religion
new-item -type directory -path $folder\$root2\216_No_longer_used_formerly_Evil
new-item -type directory -path $folder\$root2\217_No_longer_used_formerly_Prayer
new-item -type directory -path $folder\$root2\218_Humankind
new-item -type directory -path $folder\$root2\219_No_longer_used_formerly_Analogies
new-item -type directory -path $folder\$root2\220_The_Bible
new-item -type directory -path $folder\$root2\220_Bible
new-item -type directory -path $folder\$root2\221_Old_Testament
new-item -type directory -path $folder\$root2\222_Historical_books_of_Old_Testament
new-item -type directory -path $folder\$root2\223_Poetic_books_of_Old_Testament
new-item -type directory -path $folder\$root2\224_Prophetic_books_of_Old_Testament
new-item -type directory -path $folder\$root2\225_New_Testament
new-item -type directory -path $folder\$root2\226_Gospels_and_Acts
new-item -type directory -path $folder\$root2\227_Epistles
new-item -type directory -path $folder\$root2\228_Revelation_Apocalypse
new-item -type directory -path $folder\$root2\229_Apocrypha_pseudepigrapha_and_inter_testamental_works
new-item -type directory -path $folder\$root2\230_Christianity
new-item -type directory -path $folder\$root2\231_God
new-item -type directory -path $folder\$root2\232_Jesus_Christ_and_his_family
new-item -type directory -path $folder\$root2\233_Humankind
new-item -type directory -path $folder\$root2\234_Salvation_and_grace
new-item -type directory -path $folder\$root2\235_Spiritual_beings
new-item -type directory -path $folder\$root2\236_Eschatology
new-item -type directory -path $folder\$root2\237_No_longer_used_formerly_Future_state
new-item -type directory -path $folder\$root2\238_Creeds_confessions_of_faith_covenants_and_catechisms
new-item -type directory -path $folder\$root2\239_Apologetics_and_polemics
new-item -type directory -path $folder\$root2\240_Christian_practice_and_observance
new-item -type directory -path $folder\$root2\240_Christian_moral_and_devotional_theology
new-item -type directory -path $folder\$root2\241_Christian_ethics
new-item -type directory -path $folder\$root2\242_Devotional_literature
new-item -type directory -path $folder\$root2\243_Evangelistic_writings_for_individuals_and_families
new-item -type directory -path $folder\$root2\244_No_longer_used_formerly_Religious_fiction
new-item -type directory -path $folder\$root2\245_No_longer_used_formerly_Hymnology
new-item -type directory -path $folder\$root2\246_Use_of_art_in_Christianity
new-item -type directory -path $folder\$root2\247_Church_furnishings_and_related_articles
new-item -type directory -path $folder\$root2\248_Christian_experience_practice_life
new-item -type directory -path $folder\$root2\249_Christian_observances_in_family_life
new-item -type directory -path $folder\$root2\250_Christian_orders_and_local_church
new-item -type directory -path $folder\$root2\250_Local_Christian_church_and_Christian_religious_orders
new-item -type directory -path $folder\$root2\251_Preaching_Homiletics
new-item -type directory -path $folder\$root2\252_Texts_of_sermons
new-item -type directory -path $folder\$root2\253_Pastoral_office_and_work_Pastoral_theology
new-item -type directory -path $folder\$root2\254_Parish_administration
new-item -type directory -path $folder\$root2\255_Religious_congregations_and_orders
new-item -type directory -path $folder\$root2\256_No_longer_used___formerly_Religious_societies
new-item -type directory -path $folder\$root2\257_No_longer_used___formerly_Parochial_schools_libraries_etc.
new-item -type directory -path $folder\$root2\258_No_longer_used___formerly_Parochial_medicine
new-item -type directory -path $folder\$root2\259_Pastoral_care_of_families_of_specific_groups_of_people
new-item -type directory -path $folder\$root2\260_Social_and_ecclesiastical_theology
new-item -type directory -path $folder\$root2\260_Christian_social_and_ecclesiastical_theology
new-item -type directory -path $folder\$root2\261_Social_theology_and_interreligious_relations_and_attitudes
new-item -type directory -path $folder\$root2\262_Ecclesiology
new-item -type directory -path $folder\$root2\263_Days_times_places_of_religious_observance
new-item -type directory -path $folder\$root2\264_Public_worship
new-item -type directory -path $folder\$root2\265_Sacraments_other_rites_and_acts
new-item -type directory -path $folder\$root2\266_Missions
new-item -type directory -path $folder\$root2\267_Associations_for_religious_work
new-item -type directory -path $folder\$root2\268_Religious_education
new-item -type directory -path $folder\$root2\269_Spiritual_renewal
new-item -type directory -path $folder\$root2\270_History_of_Christianity
new-item -type directory -path $folder\$root2\270_History_geographic_treatment_biography_of_Christianity
new-item -type directory -path $folder\$root2\271_Religious_congregations_and_orders_in_church_history
new-item -type directory -path $folder\$root2\272_Persecutions_in_church_history
new-item -type directory -path $folder\$root2\273_Doctrinal_controversies_and_heresies_in_general_church_history
new-item -type directory -path $folder\$root2\274_Christianity_in_Europe
new-item -type directory -path $folder\$root2\275_Christianity_in_Asia
new-item -type directory -path $folder\$root2\276_Christianity_in_Africa
new-item -type directory -path $folder\$root2\277_Christianity_in_North_America
new-item -type directory -path $folder\$root2\278_Christianity_in_South_America
new-item -type directory -path $folder\$root2\279_History_of_Christianity_in_other_areas
new-item -type directory -path $folder\$root2\280_Christian_denominations
new-item -type directory -path $folder\$root2\280_Denominations_and_sects_of_Christian_church
new-item -type directory -path $folder\$root2\281_Early_church_and_Eastern_churches
new-item -type directory -path $folder\$root2\282_Roman_Catholic_Church
new-item -type directory -path $folder\$root2\283_Anglican_churches
new-item -type directory -path $folder\$root2\284_Protestant_denominations_of_Continental_origin_and_related_body
new-item -type directory -path $folder\$root2\285_Presbyterian_churches_Reformed_churches_centered_in_America_Congregational_churches
new-item -type directory -path $folder\$root2\286_Baptist_Restoration_Movement_Adventist_churches
new-item -type directory -path $folder\$root2\287_Methodist_churches_churches_related_to_Methodism
new-item -type directory -path $folder\$root2\288_No_longer_used___formerly_Unitarian
new-item -type directory -path $folder\$root2\289_Other_denominations_and_sects
new-item -type directory -path $folder\$root2\290_Other_religions
new-item -type directory -path $folder\$root2\291_No_longer_used___formerly_Comparative_religion
new-item -type directory -path $folder\$root2\292_Classical_religion_Greek_and_Roman_religion
new-item -type directory -path $folder\$root2\293_Germanic_religion
new-item -type directory -path $folder\$root2\294_Religions_of_Indic_origin
new-item -type directory -path $folder\$root2\295_Zoroastrianism_Mazdaism_Parseeism
new-item -type directory -path $folder\$root2\296_Judaism
new-item -type directory -path $folder\$root2\297_Islam_Babism_and_Bahai_Faith
new-item -type directory -path $folder\$root2\298_No_longer_used___formerly_Mormonism
new-item -type directory -path $folder\$root2\299_Religions_not_provided_for_elsewhere
new-item -type directory -path $folder\$root3\300_Social_sciences_sociology_and_anthropology
new-item -type directory -path $folder\$root3\300_Social_sciences
new-item -type directory -path $folder\$root3\301_Sociology_and_anthropology
new-item -type directory -path $folder\$root3\302_Social_interaction
new-item -type directory -path $folder\$root3\303_Social_processes
new-item -type directory -path $folder\$root3\304_Factors_affecting_social_behavior
new-item -type directory -path $folder\$root3\305_Groups_of_people
new-item -type directory -path $folder\$root3\306_Culture_and_institutions
new-item -type directory -path $folder\$root3\307_Communities
new-item -type directory -path $folder\$root3\308_No_longer_used___formerly_Polygraphy
new-item -type directory -path $folder\$root3\309_No_longer_used___formerly_History_of_sociology
new-item -type directory -path $folder\$root3\310_Statistics
new-item -type directory -path $folder\$root3\310_Collections_of_general_statistics
new-item -type directory -path $folder\$root3\311_No_longer_used___formerly_Theory_and_methods
new-item -type directory -path $folder\$root3\312_No_longer_used___formerly_Population
new-item -type directory -path $folder\$root3\313_No_longer_used___formerly_Special_topics
new-item -type directory -path $folder\$root3\314_General_statistics_of_Europe
new-item -type directory -path $folder\$root3\315_General_statistics_of_Asia
new-item -type directory -path $folder\$root3\316_General_statistics_of_Africa
new-item -type directory -path $folder\$root3\317_General_statistics_of_North_America
new-item -type directory -path $folder\$root3\318_General_statistics_of_South_America
new-item -type directory -path $folder\$root3\319_General_statistics_of_Australasia_Pacific_Ocean_islands_Atlantic_Ocean_islands_Arctic_islands_Antarctica
new-item -type directory -path $folder\$root3\320_Political_science
new-item -type directory -path $folder\$root3\320_Political_science_Politics_and_government
new-item -type directory -path $folder\$root3\321_Systems_of_governments_and_states
new-item -type directory -path $folder\$root3\322_Relation_of_state_to_organized_groups_and_their_members
new-item -type directory -path $folder\$root3\323_Civil_and_political_rights
new-item -type directory -path $folder\$root3\324_The_political_process
new-item -type directory -path $folder\$root3\325_International_migration_and_colonization
new-item -type directory -path $folder\$root3\326_Slavery_and_emancipation
new-item -type directory -path $folder\$root3\327_International_relations
new-item -type directory -path $folder\$root3\328_The_legislative_process
new-item -type directory -path $folder\$root3\329_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root3\330_Economics
new-item -type directory -path $folder\$root3\331_Labor_economics
new-item -type directory -path $folder\$root3\332_Financial_economics
new-item -type directory -path $folder\$root3\333_Economics_of_land_and_energy
new-item -type directory -path $folder\$root3\334_Cooperatives
new-item -type directory -path $folder\$root3\335_Socialism_and_related_systems
new-item -type directory -path $folder\$root3\336_Public_finance
new-item -type directory -path $folder\$root3\337_International_economics
new-item -type directory -path $folder\$root3\338_Production
new-item -type directory -path $folder\$root3\339_Macroeconomics_and_related_topics
new-item -type directory -path $folder\$root3\340_Law
new-item -type directory -path $folder\$root3\341_Law_of_nations
new-item -type directory -path $folder\$root3\342_Constitutional_and_administrative_law
new-item -type directory -path $folder\$root3\343_Military_defense_public_property_public_finance_tax_commerce_trade_industrial_law
new-item -type directory -path $folder\$root3\344_Labor_social_service_education_cultural_law
new-item -type directory -path $folder\$root3\345_Criminal_law
new-item -type directory -path $folder\$root3\346_Private_law
new-item -type directory -path $folder\$root3\347_Procedure_and_courts
new-item -type directory -path $folder\$root3\348_Laws_regulations_cases
new-item -type directory -path $folder\$root3\349_Law_of_specific_jurisdictions_areas_socioeconomic_regions_regional_intergovernmental_organizations
new-item -type directory -path $folder\$root3\350_Public_administration_and_military_science
new-item -type directory -path $folder\$root3\351_Public_administration
new-item -type directory -path $folder\$root3\352_General_considerations_of_public_administration
new-item -type directory -path $folder\$root3\353_Specific_fields_of_public_administration
new-item -type directory -path $folder\$root3\354_Public_administration_of_economy_and_environment
new-item -type directory -path $folder\$root3\355_Military_science
new-item -type directory -path $folder\$root3\356_Foot_forces_and_warfare
new-item -type directory -path $folder\$root3\357_Mounted_forces_and_warfare
new-item -type directory -path $folder\$root3\358_Air_and_other_specialized_forces_and_warfare_engineering_and_related_services
new-item -type directory -path $folder\$root3\359_Sea_forces_and_warfare
new-item -type directory -path $folder\$root3\360_Social_problems_and_social_services
new-item -type directory -path $folder\$root3\360_Social_problems_and_services_associations
new-item -type directory -path $folder\$root3\361_Social_problems_and_services
new-item -type directory -path $folder\$root3\362_Social_problems_of_and_services_to_groups_of_people
new-item -type directory -path $folder\$root3\363_Other_social_problems_and_services
new-item -type directory -path $folder\$root3\364_Criminology
new-item -type directory -path $folder\$root3\365_Penal_and_related_institutions
new-item -type directory -path $folder\$root3\366_Secret_associations_and_societies
new-item -type directory -path $folder\$root3\367_General_clubs
new-item -type directory -path $folder\$root3\368_Insurance
new-item -type directory -path $folder\$root3\369_Associations
new-item -type directory -path $folder\$root3\370_Education
new-item -type directory -path $folder\$root3\371_Schools_and_their_activities_special_education
new-item -type directory -path $folder\$root3\372_Primary_education_elementary_education
new-item -type directory -path $folder\$root3\373_Secondary_education
new-item -type directory -path $folder\$root3\374_Adult_education
new-item -type directory -path $folder\$root3\375_Curricula
new-item -type directory -path $folder\$root3\376_No_longer_used___formerly_Education_of_women
new-item -type directory -path $folder\$root3\377_No_longer_used___formerly_Ethical_education
new-item -type directory -path $folder\$root3\378_Higher_education_Tertiary_education
new-item -type directory -path $folder\$root3\379_Public_policy_issues_in_education
new-item -type directory -path $folder\$root3\380_Commerce_communications_and_transportation
new-item -type directory -path $folder\$root3\380_Commerce_communications_transportation
new-item -type directory -path $folder\$root3\381_Commerce_Trade
new-item -type directory -path $folder\$root3\382_International_commerce_Foreign_trade
new-item -type directory -path $folder\$root3\383_Postal_communication
new-item -type directory -path $folder\$root3\384_Communications
new-item -type directory -path $folder\$root3\385_Railroad_transportation
new-item -type directory -path $folder\$root3\386_Inland_waterway_and_ferry_transportation
new-item -type directory -path $folder\$root3\387_Water_air_space_transportation
new-item -type directory -path $folder\$root3\388_Transportation
new-item -type directory -path $folder\$root3\389_Metrology_and_standardization
new-item -type directory -path $folder\$root3\390_Customs_etiquette_and_folklore
new-item -type directory -path $folder\$root3\390_Customs_etiquette_folklore
new-item -type directory -path $folder\$root3\391_Costume_and_personal_appearance
new-item -type directory -path $folder\$root3\392_Customs_of_life_cycle_and_domestic_life
new-item -type directory -path $folder\$root3\393_Death_customs
new-item -type directory -path $folder\$root3\394_General_customs
new-item -type directory -path $folder\$root3\395_Etiquette_Manners
new-item -type directory -path $folder\$root3\396_No_longer_used___formerly_Womens_position_and_treatment
new-item -type directory -path $folder\$root3\397_No_longer_used___formerly_outcast_studies
new-item -type directory -path $folder\$root3\398_Folklore
new-item -type directory -path $folder\$root3\399_Customs_of_war_and_diplomacy
new-item -type directory -path $folder\$root4\400_Language
new-item -type directory -path $folder\$root4\401_Philosophy_and_theory_international_languages
new-item -type directory -path $folder\$root4\402_Miscellany
new-item -type directory -path $folder\$root4\403_Dictionaries_encyclopedias_concordances
new-item -type directory -path $folder\$root4\404_Special_topics_of_language
new-item -type directory -path $folder\$root4\405_Serial_publications
new-item -type directory -path $folder\$root4\406_Organizations_and_management
new-item -type directory -path $folder\$root4\407_Education_research_related_topics
new-item -type directory -path $folder\$root4\408_Groups_of_people
new-item -type directory -path $folder\$root4\409_Geographic_treatment_and_biography
new-item -type directory -path $folder\$root4\410_Linguistics
new-item -type directory -path $folder\$root4\411_Writing_systems_of_standard_forms_of_languages
new-item -type directory -path $folder\$root4\412_Etymology_of_standard_forms_of_languages
new-item -type directory -path $folder\$root4\413_Dictionaries_of_standard_forms_of_languages
new-item -type directory -path $folder\$root4\414_Phonology_and_phonetics_of_standard_forms_of_languages
new-item -type directory -path $folder\$root4\415_Grammar_of_standard_forms_of_languages
new-item -type directory -path $folder\$root4\416_No_longer_used___formerly_Prosody
new-item -type directory -path $folder\$root4\417_Dialectology_and_historical_linguistics
new-item -type directory -path $folder\$root4\418_Standard_usage_Prescriptive_linguistics
new-item -type directory -path $folder\$root4\419_Sign_languages
new-item -type directory -path $folder\$root4\420_English_and_Old_English_languages
new-item -type directory -path $folder\$root4\420_English_and_Old_English_Anglo_Saxon
new-item -type directory -path $folder\$root4\421_Writing_system_phonology_phonetics_of_standard_English
new-item -type directory -path $folder\$root4\422_Etymology_of_standard_English
new-item -type directory -path $folder\$root4\423_Dictionaries_of_standard_English
new-item -type directory -path $folder\$root4\424_No_longer_used___formerly_English_thesauruses
new-item -type directory -path $folder\$root4\425_Grammar_of_standard_English
new-item -type directory -path $folder\$root4\426_No_longer_used___formerly_English_prosodies
new-item -type directory -path $folder\$root4\427_Historical_and_geographical_variations_modern_nongeographic_variations_of_English
new-item -type directory -path $folder\$root4\428_Standard_English_usage_Prescriptive_linguistics
new-item -type directory -path $folder\$root4\429_Old_English_Anglo_Saxon
new-item -type directory -path $folder\$root4\430_German_and_related_languages
new-item -type directory -path $folder\$root4\431_Writing_systems_phonology_phonetics_of_standard_German
new-item -type directory -path $folder\$root4\432_Etymology_of_standard_German
new-item -type directory -path $folder\$root4\433_Dictionaries_of_standard_German
new-item -type directory -path $folder\$root4\434_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\435_Grammar_of_standard_German
new-item -type directory -path $folder\$root4\436_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\437_Historical_and_geographic_variations_modern_nongeographic_variations_of_German
new-item -type directory -path $folder\$root4\438_Standard_German_usage_Prescriptive_linguistics
new-item -type directory -path $folder\$root4\439_Other_Germanic_languages
new-item -type directory -path $folder\$root4\440_French_and_related_languages
new-item -type directory -path $folder\$root4\440_French_and_related_Romance_languages
new-item -type directory -path $folder\$root4\441_Writing_systems_phonology_phonetics_of_standard_French
new-item -type directory -path $folder\$root4\442_Etymology_of_standard_French
new-item -type directory -path $folder\$root4\443_Dictionaries_of_standard_French
new-item -type directory -path $folder\$root4\444_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\445_Grammar_of_standard_French
new-item -type directory -path $folder\$root4\446_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\447_Historical_and_geographic_variations_modern_nongeographic_variations_of_French
new-item -type directory -path $folder\$root4\448_Standard_French_usage_Prescriptive_linguistics
new-item -type directory -path $folder\$root4\449_Occitan_Catalan_Franco_Provencal
new-item -type directory -path $folder\$root4\450_Italian_Romanian_and_related_languages
new-item -type directory -path $folder\$root4\450_Italian_Dalmatian_Romanian_Rhaetian_Sardinian_Corsican
new-item -type directory -path $folder\$root4\451_Writing_systems_phonology_phonetics_of_standard_Italian
new-item -type directory -path $folder\$root4\452_Etymology_of_standard_Italian
new-item -type directory -path $folder\$root4\453_Dictionaries_of_standard_Italian
new-item -type directory -path $folder\$root4\454_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\455_Grammar_of_standard_Italian
new-item -type directory -path $folder\$root4\456_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\457_Historical_and_geographic_variations_modern_nongeographic_variations_of_Italian
new-item -type directory -path $folder\$root4\458_Standard_Italian_usage_Prescriptive_linguistics
new-item -type directory -path $folder\$root4\459_Romanian_Rhaetian_Sardinian_Corsican
new-item -type directory -path $folder\$root4\460_Spanish_Portuguese_Galician
new-item -type directory -path $folder\$root4\461_Writing_systems_phonology_phonetics_of_standard_Spanish
new-item -type directory -path $folder\$root4\462_Etymology_of_standard_Spanish
new-item -type directory -path $folder\$root4\463_Dictionaries_of_standard_Spanish
new-item -type directory -path $folder\$root4\464_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\465_Grammar_of_standard_Spanish
new-item -type directory -path $folder\$root4\466_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\467_Historical_and_geographic_variations_modern_nongeographic_variations_of_Spanish
new-item -type directory -path $folder\$root4\468_Standard_Spanish_usage_Prescriptive_linguistics
new-item -type directory -path $folder\$root4\469_Portuguese
new-item -type directory -path $folder\$root4\470_Latin_and_Italic_languages
new-item -type directory -path $folder\$root4\470_Latin_and_related_Italic_languages
new-item -type directory -path $folder\$root4\471_Writing_systems_phonology_phonetics_of_classical_Latin
new-item -type directory -path $folder\$root4\472_Etymology_of_classical_Latin
new-item -type directory -path $folder\$root4\473_Dictionaries_of_classical_Latin
new-item -type directory -path $folder\$root4\474_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\475_Grammar_of_classical_Latin
new-item -type directory -path $folder\$root4\476_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\477_Old_postclassical_Vulgar_Latin
new-item -type directory -path $folder\$root4\478_Classical_Latin_usage_Prescriptive_linguistics
new-item -type directory -path $folder\$root4\479_Other_Italic_languages
new-item -type directory -path $folder\$root4\480_Classical_and_modern_Greek_languages
new-item -type directory -path $folder\$root4\480_Classical_Greek_and_related_Hellenic_languages
new-item -type directory -path $folder\$root4\481_Writing_systems_phonology_phonetics_of_classical_Greek
new-item -type directory -path $folder\$root4\482_Etymology_of_classical_Greek
new-item -type directory -path $folder\$root4\483_Dictionaries_of_classical_Greek
new-item -type directory -path $folder\$root4\484_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\485_Grammar_of_classical_Greek
new-item -type directory -path $folder\$root4\486_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root4\487_Preclassical_and_postclassical_Greek
new-item -type directory -path $folder\$root4\488_Classical_Greek_usage_Prescriptive_linguistics
new-item -type directory -path $folder\$root4\489_Other_Hellenic_languages
new-item -type directory -path $folder\$root4\490_Other_languages
new-item -type directory -path $folder\$root4\491_East_Indo_European_and_Celtic_languages
new-item -type directory -path $folder\$root4\492_Afro_Asiatic_languages
new-item -type directory -path $folder\$root4\493_Non_Semitic_Afro_Asiatic_languages
new-item -type directory -path $folder\$root4\494_Altic_Uralic_Hyperborean_Dravidian_languages_miscellaneous_languages_of_south_Asia
new-item -type directory -path $folder\$root4\495_Languages_of_East_and_Southeast_Asia
new-item -type directory -path $folder\$root4\496_African_languages
new-item -type directory -path $folder\$root4\497_North_American_native_languages
new-item -type directory -path $folder\$root4\498_South_American_native_languages
new-item -type directory -path $folder\$root4\499_Non_Austronesian_languages_of_Oceania_Austronesian_languages_miscellaneous_languages
new-item -type directory -path $folder\$root5\500_Science
new-item -type directory -path $folder\$root5\500_Natural_sciences_and_mathematics
new-item -type directory -path $folder\$root5\501_Philosophy_and_theory
new-item -type directory -path $folder\$root5\502_Miscellany
new-item -type directory -path $folder\$root5\503_Dictionaries_encyclopedias_concordances
new-item -type directory -path $folder\$root5\504_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root5\505_Serial_publications
new-item -type directory -path $folder\$root5\506_Organizations_and_management
new-item -type directory -path $folder\$root5\507_Education_research_related_topics
new-item -type directory -path $folder\$root5\508_Natural_history
new-item -type directory -path $folder\$root5\509_History_geographic_treatment_biography
new-item -type directory -path $folder\$root5\510_Mathematics
new-item -type directory -path $folder\$root5\511_General_principles_of_mathematics
new-item -type directory -path $folder\$root5\512_Algebra
new-item -type directory -path $folder\$root5\513_Arithmetic
new-item -type directory -path $folder\$root5\514_Topology
new-item -type directory -path $folder\$root5\515_Analysis
new-item -type directory -path $folder\$root5\516_Geometry
new-item -type directory -path $folder\$root5\517_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root5\518_Numerical_analysis
new-item -type directory -path $folder\$root5\519_Probabilities_and_applied_mathematics
new-item -type directory -path $folder\$root5\520_Astronomy
new-item -type directory -path $folder\$root5\520_Astronomy_and_allied_sciences
new-item -type directory -path $folder\$root5\521_Celestial_mechanics
new-item -type directory -path $folder\$root5\522_Techniques_procedures_apparatus_equipment_materials
new-item -type directory -path $folder\$root5\523_Specific_celestial_bodies_and_phenomena
new-item -type directory -path $folder\$root5\524_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root5\525_Earth_Astronomical_geography
new-item -type directory -path $folder\$root5\526_Mathematical_geography
new-item -type directory -path $folder\$root5\527_Celestial_navigation
new-item -type directory -path $folder\$root5\528_Ephemerides
new-item -type directory -path $folder\$root5\529_Chronology
new-item -type directory -path $folder\$root5\530_Physics
new-item -type directory -path $folder\$root5\531_Classical_mechanics
new-item -type directory -path $folder\$root5\532_Fluid_mechanics
new-item -type directory -path $folder\$root5\533_Pneumatics_Gas_mechanics
new-item -type directory -path $folder\$root5\534_Sound_and_related_vibrations
new-item -type directory -path $folder\$root5\535_Light_and_related_radiation
new-item -type directory -path $folder\$root5\536_Heat
new-item -type directory -path $folder\$root5\537_Electricity_and_electronics
new-item -type directory -path $folder\$root5\538_Magnetism
new-item -type directory -path $folder\$root5\539_Modern_physics
new-item -type directory -path $folder\$root5\540_Chemistry
new-item -type directory -path $folder\$root5\540_Chemistry_and_allied_sciences
new-item -type directory -path $folder\$root5\541_Physical_chemistry
new-item -type directory -path $folder\$root5\542_Techniques_procedures_apparatus_equipment_materials
new-item -type directory -path $folder\$root5\543_Analytical_chemistry
new-item -type directory -path $folder\$root5\544_No_longer_used___formerly_Qualitative_analysis
new-item -type directory -path $folder\$root5\545_No_longer_used___formerly_Quantitative_analysis
new-item -type directory -path $folder\$root5\546_Inorganic_chemistry
new-item -type directory -path $folder\$root5\547_Organic_chemistry
new-item -type directory -path $folder\$root5\548_Crystallography
new-item -type directory -path $folder\$root5\549_Mineralogy
new-item -type directory -path $folder\$root5\550_Earth_sciences_and_geology
new-item -type directory -path $folder\$root5\550_Earth_sciences
new-item -type directory -path $folder\$root5\551_Geology_hydrology_meteorology
new-item -type directory -path $folder\$root5\552_Petrology
new-item -type directory -path $folder\$root5\553_Economic_geology
new-item -type directory -path $folder\$root5\554_Earth_sciences_of_Europe
new-item -type directory -path $folder\$root5\555_Earth_sciences_of_Asia
new-item -type directory -path $folder\$root5\556_Earth_sciences_of_Africa
new-item -type directory -path $folder\$root5\557_Earth_sciences_of_North_America
new-item -type directory -path $folder\$root5\558_Earth_sciences_of_South_America
new-item -type directory -path $folder\$root5\559_Earth_sciences_of_Australasia_Pacific_Ocean_islands_Atlantic_Ocean_islands_Arctic_islands_Antarctica_extraterrestrial_worlds
new-item -type directory -path $folder\$root5\560_Fossils_and_prehistoric_life
new-item -type directory -path $folder\$root5\560_Paleontology
new-item -type directory -path $folder\$root5\561_Paleobotany_fossil_microorganisms
new-item -type directory -path $folder\$root5\562_Fossil_invertebrates
new-item -type directory -path $folder\$root5\563_Miscellaneous_fossil_marine_and_seashore_invertebrates
new-item -type directory -path $folder\$root5\564_Fossil_Mollusca_and_Molluscoidea
new-item -type directory -path $folder\$root5\565_Fossil_Arthropoda
new-item -type directory -path $folder\$root5\566_Fossil_Chordata
new-item -type directory -path $folder\$root5\567_Fossil_cold_blooded_vertebrates
new-item -type directory -path $folder\$root5\568_Fossil_Aves_birds
new-item -type directory -path $folder\$root5\569_Fossil_Mammalia
new-item -type directory -path $folder\$root5\570_Biology
new-item -type directory -path $folder\$root5\571_Physiology_and_related_subjects
new-item -type directory -path $folder\$root5\572_Biochemistry
new-item -type directory -path $folder\$root5\573_Specific_physiological_systems_in_animals_regional_histology_and_physiology_in_animals
new-item -type directory -path $folder\$root5\574_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root5\575_Specific_parts_of_and_physiological_systems_in_plants
new-item -type directory -path $folder\$root5\576_Genetics_and_evolution
new-item -type directory -path $folder\$root5\577_Ecology
new-item -type directory -path $folder\$root5\578_Natural_history_of_organisms_and_related_subjects
new-item -type directory -path $folder\$root5\579_Natural_history_of_microorganisms_fungi_algae
new-item -type directory -path $folder\$root5\580_Plants
new-item -type directory -path $folder\$root5\581_Specific_topics_in_natural_history_of_plants
new-item -type directory -path $folder\$root5\582_Plants_noted_for_specific_vegetative_characteristics_and_flowers
new-item -type directory -path $folder\$root5\583_Magnoliopsida_Dicotyledones
new-item -type directory -path $folder\$root5\584_Liliopsida_Monocotyledones
new-item -type directory -path $folder\$root5\585_Pinophyta_Gymnosperms
new-item -type directory -path $folder\$root5\586_Cryptogamia_Seedless_plants
new-item -type directory -path $folder\$root5\587_Pteridophyta
new-item -type directory -path $folder\$root5\588_Bryophyta
new-item -type directory -path $folder\$root5\589_No_longer_used_formerly_Forestry
new-item -type directory -path $folder\$root5\590_Animals_Zoology
new-item -type directory -path $folder\$root5\590_Animals
new-item -type directory -path $folder\$root5\591_Specific_topics_in_natural_history_of_animals
new-item -type directory -path $folder\$root5\592_Invertebrates
new-item -type directory -path $folder\$root5\593_Miscellaneous_marine_and_seashore_invertebrates
new-item -type directory -path $folder\$root5\594_Mollusca_and_Molluscoidea
new-item -type directory -path $folder\$root5\595_Arthropoda
new-item -type directory -path $folder\$root5\596_Chordata
new-item -type directory -path $folder\$root5\597_Cold_blooded_vertebrates
new-item -type directory -path $folder\$root5\598_Aves_Birds
new-item -type directory -path $folder\$root5\599_Mammalia_Mammals
new-item -type directory -path $folder\$root6\600_Technology
new-item -type directory -path $folder\$root6\600_Technology_Applied_sciences
new-item -type directory -path $folder\$root6\601_Philosophy_and_theory
new-item -type directory -path $folder\$root6\602_Miscellany
new-item -type directory -path $folder\$root6\603_Dictionaries_encyclopedias_concordances
new-item -type directory -path $folder\$root6\604_Technical_drawing_hazardous_materials_technology_groups_of_people
new-item -type directory -path $folder\$root6\605_Serial_publications
new-item -type directory -path $folder\$root6\606_Organizations
new-item -type directory -path $folder\$root6\607_Education_research_related_topics
new-item -type directory -path $folder\$root6\608_Patents
new-item -type directory -path $folder\$root6\609_History_geographic_treatment_biography
new-item -type directory -path $folder\$root6\610_Medicine_and_health
new-item -type directory -path $folder\$root6\611_Human_anatomy_cytology_histology
new-item -type directory -path $folder\$root6\612_Human_physiology
new-item -type directory -path $folder\$root6\613_Personal_health_and_safety
new-item -type directory -path $folder\$root6\614_Forensic_medicine_incidence_of_injuries_wounds_disease_public_preventive_medicine
new-item -type directory -path $folder\$root6\615_Pharmacology_and_therapeutics
new-item -type directory -path $folder\$root6\616_Diseases
new-item -type directory -path $folder\$root6\617_Surgery_regional_medicine_dentistry_ophthalmology_otology_audiology
new-item -type directory -path $folder\$root6\618_Gynecology_obstetrics_pediatrics_geriatrics
new-item -type directory -path $folder\$root6\619_No_longer_used_formerly_Experimental_medicine
new-item -type directory -path $folder\$root6\620_Engineering
new-item -type directory -path $folder\$root6\620_Engineering_and_applied_operations
new-item -type directory -path $folder\$root6\621_Applied_physics
new-item -type directory -path $folder\$root6\622_Mining_and_related_operations
new-item -type directory -path $folder\$root6\623_Military_and_nautical_engineering
new-item -type directory -path $folder\$root6\624_Civil_engineering
new-item -type directory -path $folder\$root6\625_Engineering_of_railroads_roads
new-item -type directory -path $folder\$root6\626_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root6\627_Hydraulic_engineering
new-item -type directory -path $folder\$root6\628_Sanitary_engineering
new-item -type directory -path $folder\$root6\629_Other_branches_of_engineering
new-item -type directory -path $folder\$root6\630_Agriculture
new-item -type directory -path $folder\$root6\630_Agriculture_and_related_technologies
new-item -type directory -path $folder\$root6\631_Specific_techniques_apparatus_equipment_materials
new-item -type directory -path $folder\$root6\632_Plant_injuries_diseases_pests
new-item -type directory -path $folder\$root6\633_Field_and_plantation_crops
new-item -type directory -path $folder\$root6\634_Orchards_fruits_forestry
new-item -type directory -path $folder\$root6\635_Garden_crops_Horticulture
new-item -type directory -path $folder\$root6\636_Animal_husbandry
new-item -type directory -path $folder\$root6\637_Processing_dairy_and_related_products
new-item -type directory -path $folder\$root6\638_Insect_culture
new-item -type directory -path $folder\$root6\639_Hunting_fishing_conservation_related_technologies
new-item -type directory -path $folder\$root6\640_Home_and_family_management
new-item -type directory -path $folder\$root6\641_Food_and_drink
new-item -type directory -path $folder\$root6\642_Meals_and_table_service
new-item -type directory -path $folder\$root6\643_Housing_and_household_equipment
new-item -type directory -path $folder\$root6\644_Household_utilities
new-item -type directory -path $folder\$root6\645_Household_furnishings
new-item -type directory -path $folder\$root6\646_Sewing_clothing_management_of_personal_and_family_life
new-item -type directory -path $folder\$root6\647_Management_of_public_households_Institutional_housekeeping
new-item -type directory -path $folder\$root6\648_Housekeeping
new-item -type directory -path $folder\$root6\649_Child_rearing_home_care_of_people_with_disabilities_and_illnesses
new-item -type directory -path $folder\$root6\650_Management_and_public_relations
new-item -type directory -path $folder\$root6\650_Management_and_auxiliary_services
new-item -type directory -path $folder\$root6\651_Office_services
new-item -type directory -path $folder\$root6\652_Processes_of_written_communication
new-item -type directory -path $folder\$root6\653_Shorthand
new-item -type directory -path $folder\$root6\654_656_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root6\657_Accounting
new-item -type directory -path $folder\$root6\658_General_management
new-item -type directory -path $folder\$root6\659_Advertising_and_public_relations
new-item -type directory -path $folder\$root6\660_Chemical_engineering
new-item -type directory -path $folder\$root6\660_Chemical_engineering_and_related_technologies
new-item -type directory -path $folder\$root6\661_Technology_of_industrial_chemicals
new-item -type directory -path $folder\$root6\662_Technology_of_explosives_fuels_related_products
new-item -type directory -path $folder\$root6\663_Beverage_technology
new-item -type directory -path $folder\$root6\664_Food_technology
new-item -type directory -path $folder\$root6\665_Technology_of_industrial_oils_fats_waxes_gases
new-item -type directory -path $folder\$root6\666_Ceramic_and_allied_technologies
new-item -type directory -path $folder\$root6\667_Cleaning_color_coating_related_technologies
new-item -type directory -path $folder\$root6\668_Technology_of_other_organic_products
new-item -type directory -path $folder\$root6\669_Metallurgy
new-item -type directory -path $folder\$root6\670_Manufacturing
new-item -type directory -path $folder\$root6\671_Metalworking_processes_and_primary_metal_products
new-item -type directory -path $folder\$root6\672_Iron_steel_other_iron_alloys
new-item -type directory -path $folder\$root6\673_Nonferrous_metals
new-item -type directory -path $folder\$root6\674_Lumber_processing_wood_products_cork
new-item -type directory -path $folder\$root6\675_Leather_and_fur_processing
new-item -type directory -path $folder\$root6\676_Pulp_and_paper_technology
new-item -type directory -path $folder\$root6\677_Textiles
new-item -type directory -path $folder\$root6\678_Elastomers_and_elastomer_products
new-item -type directory -path $folder\$root6\679_Other_products_of_specific_kinds_of_materials
new-item -type directory -path $folder\$root6\680_Manufacture_for_specific_uses
new-item -type directory -path $folder\$root6\680_Manufacture_of_products_for_specific_uses
new-item -type directory -path $folder\$root6\681_Precision_instruments_and_other_devices
new-item -type directory -path $folder\$root6\682_Small_forge_work_Blacksmithing
new-item -type directory -path $folder\$root6\683_Hardware_and_household_appliances
new-item -type directory -path $folder\$root6\684_Furnishings_and_home_workshops
new-item -type directory -path $folder\$root6\685_Leather_and_fur_goods_and_related_products
new-item -type directory -path $folder\$root6\686_Printing_and_related_activities
new-item -type directory -path $folder\$root6\687_Clothing_and_accessories
new-item -type directory -path $folder\$root6\688_Other_final_products_and_packaging_technology
new-item -type directory -path $folder\$root6\689_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root6\690_Construction_of_buildings
new-item -type directory -path $folder\$root6\691_Building_materials
new-item -type directory -path $folder\$root6\692_Auxiliary_construction_practices
new-item -type directory -path $folder\$root6\693_Construction_in_specific_types_of_materials_and_for_specific_purposes
new-item -type directory -path $folder\$root6\694_Wood_construction
new-item -type directory -path $folder\$root6\695_Roof_covering
new-item -type directory -path $folder\$root6\696_Utilities
new-item -type directory -path $folder\$root6\697_Heating_ventilating_air_conditioning_engineering
new-item -type directory -path $folder\$root6\698_Detail_finishing
new-item -type directory -path $folder\$root6\699_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root7\700_Arts
new-item -type directory -path $folder\$root7\700_The_Arts
new-item -type directory -path $folder\$root7\701_Philosophy_and_theory_of_fine_and_decorative_arts
new-item -type directory -path $folder\$root7\702_Miscellany_of_fine_and_decorative_arts
new-item -type directory -path $folder\$root7\703_Dictionaries_encyclopedias_concordances_of_fine_and_decorative_arts
new-item -type directory -path $folder\$root7\704_Special_topics_in_fine_and_decorative_arts
new-item -type directory -path $folder\$root7\705_Serial_publications_of_fine_and_decorative_arts
new-item -type directory -path $folder\$root7\706_Organizations_and_management_of_fine_and_decorative_arts
new-item -type directory -path $folder\$root7\707_Education_research_related_topics_of_fine_and_decorative_arts
new-item -type directory -path $folder\$root7\708_Galleries_museums_private_collections_of_fine_and_decorative_arts
new-item -type directory -path $folder\$root7\709_History_geographic_treatment_biography
new-item -type directory -path $folder\$root7\710_Area_planning_and_landscape_architecture
new-item -type directory -path $folder\$root7\711_Area_planning_Civic_art
new-item -type directory -path $folder\$root7\712_Landscape_architecture_Landscape_design
new-item -type directory -path $folder\$root7\713_Landscape_architecture_of_trafficways
new-item -type directory -path $folder\$root7\714_Water_features_in_landscape_architecture
new-item -type directory -path $folder\$root7\715_Woody_plants_in_landscape_architecture
new-item -type directory -path $folder\$root7\716_Herbaceous_plants_in_landscape_architecture
new-item -type directory -path $folder\$root7\717_Structures_in_landscape_architecture
new-item -type directory -path $folder\$root7\718_Landscape_design_of_cemeteries
new-item -type directory -path $folder\$root7\719_Natural_landscapes
new-item -type directory -path $folder\$root7\720_Architecture
new-item -type directory -path $folder\$root7\721_Architectural_materials_and_structural_elements
new-item -type directory -path $folder\$root7\722_Architecture_from_earliest_times_to_c_300
new-item -type directory -path $folder\$root7\723_Architecture_from_c_300_to_1399
new-item -type directory -path $folder\$root7\724_Architecture_from_1400
new-item -type directory -path $folder\$root7\725_Public_structures
new-item -type directory -path $folder\$root7\726_Buildings_for_religious_and_related_purposes
new-item -type directory -path $folder\$root7\727_Buildings_for_educational_and_research_purposes
new-item -type directory -path $folder\$root7\728_Residential_and_related_buildings
new-item -type directory -path $folder\$root7\729_Design_and_decoration_of_structures_and_accessories
new-item -type directory -path $folder\$root7\730_Sculpture_ceramics_and_metalwork
new-item -type directory -path $folder\$root7\730_Sculpture_and_related_arts
new-item -type directory -path $folder\$root7\731_Processes_forms_subjects_of_sculpture
new-item -type directory -path $folder\$root7\732_Sculpture_from_earliest_times_to_c_500_sculpture_of_non_literate_peoples
new-item -type directory -path $folder\$root7\733_Greek_Etruscan_Roman_sculpture
new-item -type directory -path $folder\$root7\734_Sculpture_from_ca_500_to_1399
new-item -type directory -path $folder\$root7\735_Sculpture_from_1400
new-item -type directory -path $folder\$root7\736_Carving_and_carvings
new-item -type directory -path $folder\$root7\737_Numismatics_and_sigillography
new-item -type directory -path $folder\$root7\738_Ceramic_arts
new-item -type directory -path $folder\$root7\739_Art_metalwork
new-item -type directory -path $folder\$root7\740_Graphic_arts_and_decorative_arts
new-item -type directory -path $folder\$root7\740_Graphic_arts
new-item -type directory -path $folder\$root7\741_Drawing_and_drawings
new-item -type directory -path $folder\$root7\742_Perspective_in_drawing
new-item -type directory -path $folder\$root7\743_Drawing_and_drawings_by_subject
new-item -type directory -path $folder\$root7\744_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root7\745_Decorative_arts
new-item -type directory -path $folder\$root7\746_Textile_arts
new-item -type directory -path $folder\$root7\747_Interior_decoration
new-item -type directory -path $folder\$root7\748_Glass
new-item -type directory -path $folder\$root7\749_Furniture_and_accessories
new-item -type directory -path $folder\$root7\750_Painting
new-item -type directory -path $folder\$root7\750_Painting_and_paintings
new-item -type directory -path $folder\$root7\751_Techniques_procedures_apparatus_equipment_materials_forms
new-item -type directory -path $folder\$root7\752_Color
new-item -type directory -path $folder\$root7\753_Symbolism_allegory_mythology_legend
new-item -type directory -path $folder\$root7\754_Genre_paintings
new-item -type directory -path $folder\$root7\755_Religion
new-item -type directory -path $folder\$root7\756_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root7\757_Human_figures
new-item -type directory -path $folder\$root7\758_Nature_architectural_subjects_and_cityscapes_other_specific_subjects
new-item -type directory -path $folder\$root7\759_History_geographic_treatment_biography
new-item -type directory -path $folder\$root7\760_Printmaking_and_prints
new-item -type directory -path $folder\$root7\761_Relief_processes_Block_printing
new-item -type directory -path $folder\$root7\762_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root7\763_Lithographic_processes_Planographic_processes
new-item -type directory -path $folder\$root7\764_Chromolithography_and_serigraphy
new-item -type directory -path $folder\$root7\765_Metal_engraving
new-item -type directory -path $folder\$root7\766_Mezzotinting_aquatinting_and_related_processes
new-item -type directory -path $folder\$root7\767_Etching_and_drypoint
new-item -type directory -path $folder\$root7\768_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root7\769_Prints
new-item -type directory -path $folder\$root7\770_Photography_computer_art_film_video
new-item -type directory -path $folder\$root7\770_Photography_computer_art_cinematography_videography
new-item -type directory -path $folder\$root7\771_Techniques_procedures_apparatus_equipment_materials
new-item -type directory -path $folder\$root7\772_Metallic_salt_processes
new-item -type directory -path $folder\$root7\773_Pigment_processes_of_printing
new-item -type directory -path $folder\$root7\774_No_longer_used_formerly_Holography
new-item -type directory -path $folder\$root7\775_No_longer_used_formerly_Digital_photography
new-item -type directory -path $folder\$root7\776_Computer_art_Digital_art
new-item -type directory -path $folder\$root7\777_Cinematography_and_Videography
new-item -type directory -path $folder\$root7\778_Specific_fields_and_special_kinds_of_photography
new-item -type directory -path $folder\$root7\779_Photographic_images
new-item -type directory -path $folder\$root7\780_Music
new-item -type directory -path $folder\$root7\781_General_principles_and_musical_forms
new-item -type directory -path $folder\$root7\782_Vocal_music
new-item -type directory -path $folder\$root7\783_Music_for_single_voices
new-item -type directory -path $folder\$root7\784_Instruments_and_Instrumental_ensembles_and_their_music
new-item -type directory -path $folder\$root7\785_Ensembles_with_only_one_instrument_per_part
new-item -type directory -path $folder\$root7\786_Keyboard_mechanical_electrophonic_percussion_instruments
new-item -type directory -path $folder\$root7\787_Stringed_instruments_Chordophones
new-item -type directory -path $folder\$root7\788_Wind_instruments_Aerophones
new-item -type directory -path $folder\$root7\789_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root7\790_Outline_of_sports_games_and_entertainment
new-item -type directory -path $folder\$root7\790_Recreational_and_performing_arts
new-item -type directory -path $folder\$root7\791_Public_performances
new-item -type directory -path $folder\$root7\792_Stage_presentations
new-item -type directory -path $folder\$root7\793_Indoor_games_and_amusements
new-item -type directory -path $folder\$root7\794_Indoor_games_of_skill
new-item -type directory -path $folder\$root7\795_Games_of_chance
new-item -type directory -path $folder\$root7\796_Athletic_and_outdoor_sports_and_games
new-item -type directory -path $folder\$root7\797_Aquatic_and_air_sports
new-item -type directory -path $folder\$root7\798_Equestrian_sports_and_animal_racing
new-item -type directory -path $folder\$root7\799_Fishing_hunting_shooting
new-item -type directory -path $folder\$root8\800_Literature_rhetoric_and_criticism
new-item -type directory -path $folder\$root8\800_Literature_Belles_lettres_and_rhetoric
new-item -type directory -path $folder\$root8\801_Philosophy_and_theory
new-item -type directory -path $folder\$root8\802_Miscellany
new-item -type directory -path $folder\$root8\803_Dictionaries_encyclopedias_concordances
new-item -type directory -path $folder\$root8\804_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root8\805_Serial_publications
new-item -type directory -path $folder\$root8\806_Organizations_and_management
new-item -type directory -path $folder\$root8\807_Education_research_related_topics
new-item -type directory -path $folder\$root8\808_Rhetoric_and_collections_of_literary_texts_from_more_than_two_literatures
new-item -type directory -path $folder\$root8\809_History_description_critical_appraisal_of_more_than_two_literatures
new-item -type directory -path $folder\$root8\810_American_literature_in_English
new-item -type directory -path $folder\$root8\811_American_poetry_in_English
new-item -type directory -path $folder\$root8\812_American_drama_in_English
new-item -type directory -path $folder\$root8\813_American_fiction_in_English
new-item -type directory -path $folder\$root8\814_American_essays_in_English
new-item -type directory -path $folder\$root8\815_American_speeches_in_English
new-item -type directory -path $folder\$root8\816_American_letters_in_English
new-item -type directory -path $folder\$root8\817_American_humor_and_satire_in_English
new-item -type directory -path $folder\$root8\818_American_miscellaneous_writings_in_English
new-item -type directory -path $folder\$root8\819_No_longer_used_formerly_Puzzle_activities
new-item -type directory -path $folder\$root8\820_English_and_Old_English_literatures
new-item -type directory -path $folder\$root8\820_English_and_Old_English_Anglo_Saxon_literatures
new-item -type directory -path $folder\$root8\821_English_Poetry
new-item -type directory -path $folder\$root8\822_English_drama
new-item -type directory -path $folder\$root8\823_English_fiction
new-item -type directory -path $folder\$root8\824_English_essays
new-item -type directory -path $folder\$root8\825_English_speeches
new-item -type directory -path $folder\$root8\826_English_letters
new-item -type directory -path $folder\$root8\827_English_humor_and_satire
new-item -type directory -path $folder\$root8\828_English_miscellaneous_writings
new-item -type directory -path $folder\$root8\829_Old_English_Anglo_Saxon_literature
new-item -type directory -path $folder\$root8\830_German_and_related_literatures
new-item -type directory -path $folder\$root8\830_German_literature_and_literatures_of_related_languages
new-item -type directory -path $folder\$root8\831_German_poetry
new-item -type directory -path $folder\$root8\832_German_drama
new-item -type directory -path $folder\$root8\833_German_fiction
new-item -type directory -path $folder\$root8\834_German_essays
new-item -type directory -path $folder\$root8\835_German_speeches
new-item -type directory -path $folder\$root8\836_German_letters
new-item -type directory -path $folder\$root8\837_German_humor_and_satire
new-item -type directory -path $folder\$root8\838_German_miscellaneous_writings
new-item -type directory -path $folder\$root8\839_Other_Germanic_literatures
new-item -type directory -path $folder\$root8\840_French_and_related_literatures
new-item -type directory -path $folder\$root8\840_French_literature_and_literatures_of_related_Romance_languages
new-item -type directory -path $folder\$root8\841_French_poetry
new-item -type directory -path $folder\$root8\842_French_drama
new-item -type directory -path $folder\$root8\843_French_fiction
new-item -type directory -path $folder\$root8\844_French_essays
new-item -type directory -path $folder\$root8\845_French_speeches
new-item -type directory -path $folder\$root8\846_French_letters
new-item -type directory -path $folder\$root8\847_French_humor_and_satire
new-item -type directory -path $folder\$root8\848_French_miscellaneous_writings
new-item -type directory -path $folder\$root8\849_Occitan_Catalan_Franco_Provencal_literatures
new-item -type directory -path $folder\$root8\850_Italian_Romanian_and_related_literatures
new-item -type directory -path $folder\$root8\850_Literatures_of_Italian_Dalmatian_Romanian_Rhaetian_Sardinian_Corsican_languages
new-item -type directory -path $folder\$root8\851_Italian_poetry
new-item -type directory -path $folder\$root8\852_Italian_drama
new-item -type directory -path $folder\$root8\853_Italian_fiction
new-item -type directory -path $folder\$root8\854_Italian_essays
new-item -type directory -path $folder\$root8\855_Italian_speeches
new-item -type directory -path $folder\$root8\856_Italian_letters
new-item -type directory -path $folder\$root8\857_Italian_humor_and_satire
new-item -type directory -path $folder\$root8\858_Italian_miscellaneous_writings
new-item -type directory -path $folder\$root8\859_Literatures_of_Romanian_Rhaetian_Sardinian_Corsican_languages
new-item -type directory -path $folder\$root8\860_Spanish_Portuguese_Galician_literatures
new-item -type directory -path $folder\$root8\860_Literatures_of_Spanish_Portuguese_Galician_languages
new-item -type directory -path $folder\$root8\861_Spanish_poetry
new-item -type directory -path $folder\$root8\862_Spanish_drama
new-item -type directory -path $folder\$root8\863_Spanish_fiction
new-item -type directory -path $folder\$root8\864_Spanish_essays
new-item -type directory -path $folder\$root8\865_Spanish_speeches
new-item -type directory -path $folder\$root8\866_Spanish_letters
new-item -type directory -path $folder\$root8\867_Spanish_humor_and_satire
new-item -type directory -path $folder\$root8\868_Spanish_miscellaneous_writings
new-item -type directory -path $folder\$root8\869_Literatures_of_Portuguese_and_Galician_languages
new-item -type directory -path $folder\$root8\870_Latin_and_Italic_literatures
new-item -type directory -path $folder\$root8\870_Latin_literature_and_literatures_of_related_Italic_languages
new-item -type directory -path $folder\$root8\871_Latin_poetry
new-item -type directory -path $folder\$root8\872_Latin_dramatic_poetry_and_drama
new-item -type directory -path $folder\$root8\873_Latin_epic_poetry_and_fiction
new-item -type directory -path $folder\$root8\874_Latin_lyric_poetry
new-item -type directory -path $folder\$root8\875_Latin_speeches
new-item -type directory -path $folder\$root8\876_Latin_letters
new-item -type directory -path $folder\$root8\877_Latin_humor_and_satire
new-item -type directory -path $folder\$root8\878_Latin_miscellaneous_writings
new-item -type directory -path $folder\$root8\879_Literatures_of_other_Italic_languages
new-item -type directory -path $folder\$root8\880_Classical_and_modern_Greek_literatures
new-item -type directory -path $folder\$root8\880_Classical_Greek_literature_and_literatures_of_related_Hellenic_languages
new-item -type directory -path $folder\$root8\881_Classical_Greek_poetry
new-item -type directory -path $folder\$root8\882_Classical_Greek_drama
new-item -type directory -path $folder\$root8\883_Classical_Greek_epic_poetry_and_fiction
new-item -type directory -path $folder\$root8\884_Classical_Greek_lyric_poetry
new-item -type directory -path $folder\$root8\885_Classical_Greek_speeches
new-item -type directory -path $folder\$root8\886_Classical_Greek_letters
new-item -type directory -path $folder\$root8\887_Classical_Greek_humor_and_satire
new-item -type directory -path $folder\$root8\888_Classical_Greek_miscellaneous_writings
new-item -type directory -path $folder\$root8\889_Modern_Greek_literature
new-item -type directory -path $folder\$root8\890_Other_literatures
new-item -type directory -path $folder\$root8\890_Literatures_of_other_specific_languages_and_language_families
new-item -type directory -path $folder\$root8\891_East_Indo_European_and_Celtic_literatures
new-item -type directory -path $folder\$root8\892_Afro_Asiatic_literatures
new-item -type directory -path $folder\$root8\893_Non_Semitic_Afro_Asiatic_literatures
new-item -type directory -path $folder\$root8\894_Literatures_of_Altaic_Uralic_Hyperborean_Dravidian_languages_literatures_of_miscellaneous_languages_of_South_Asia
new-item -type directory -path $folder\$root8\895_Literatures_of_East_and_Southeast_Asia
new-item -type directory -path $folder\$root8\896_African_literatures
new-item -type directory -path $folder\$root8\897_Literatures_of_North_American_native_languages
new-item -type directory -path $folder\$root8\898_Literatures_of_South_American_native_languages
new-item -type directory -path $folder\$root8\899_Literatures_of_non_Austronesian_languages_of_Oceania_of_Austronesian_languages_of_miscellaneous_languages
new-item -type directory -path $folder\$root9\900_History
new-item -type directory -path $folder\$root9\900_History_geography_and_auxiliary_disciplines
new-item -type directory -path $folder\$root9\901_Philosophy_and_theory_of_history
new-item -type directory -path $folder\$root9\902_Miscellany_of_history
new-item -type directory -path $folder\$root9\903_Dictionaries_encyclopedias_concordances_of_history
new-item -type directory -path $folder\$root9\904_Collected_accounts_of_events
new-item -type directory -path $folder\$root9\905_Serial_publications_of_history
new-item -type directory -path $folder\$root9\906_Organizations_and_management_of_history
new-item -type directory -path $folder\$root9\907_Education_research_related_topics_of_history
new-item -type directory -path $folder\$root9\908_History_with_respect_to_groups_of_people
new-item -type directory -path $folder\$root9\909_World_history
new-item -type directory -path $folder\$root9\910_Geography_and_travel
new-item -type directory -path $folder\$root9\911_Historical_geography
new-item -type directory -path $folder\$root9\912_Graphic_representations_of_surface_of_earth_and_of_extraterrestrial_worlds
new-item -type directory -path $folder\$root9\913_Geography_of_and_travel_in_the_ancient_world
new-item -type directory -path $folder\$root9\914_Geography_of_and_travel_in_Europe
new-item -type directory -path $folder\$root9\915_Geography_of_and_travel_in_Asia
new-item -type directory -path $folder\$root9\916_Geography_of_and_travel_in_Africa
new-item -type directory -path $folder\$root9\917_Geography_of_and_travel_in_North_America
new-item -type directory -path $folder\$root9\918_Geography_of_and_travel_in_South_America
new-item -type directory -path $folder\$root9\919_Geography_of_and_travel_in_Australasia_Pacific_Ocean_islands_Atlantic_Ocean_islands_Arctic_islands_Antarctica_and_on_extraterrestrial_worlds
new-item -type directory -path $folder\$root9\920_Biography_and_genealogy
new-item -type directory -path $folder\$root9\920_Biography_genealogy_insignia
new-item -type directory -path $folder\$root9\921_928_This_range_is_reserved_as_an_optional_location_for_biographies_which_are_shelved_alphabetically_by_subjects_last_name
new-item -type directory -path $folder\$root9\929_Genealogy_names_insignia
new-item -type directory -path $folder\$root9\930_History_of_ancient_world_to_c_499
new-item -type directory -path $folder\$root9\931_China_to_420
new-item -type directory -path $folder\$root9\932_Egypt_to_640
new-item -type directory -path $folder\$root9\933_Palestine_to_70
new-item -type directory -path $folder\$root9\934_South_Asia_to_647
new-item -type directory -path $folder\$root9\935_Mesopotamia_to_637_and_Iranian_Plateau_to_637
new-item -type directory -path $folder\$root9\936_Europe_north_and_west_of_Italian_Peninsula_to_c_499
new-item -type directory -path $folder\$root9\937_Italian_Peninsula_to_476_and_adjacent_territories_to_476
new-item -type directory -path $folder\$root9\938_Greece_to_323
new-item -type directory -path $folder\$root9\939_Other_parts_of_ancient_world
new-item -type directory -path $folder\$root9\940_History_of_Europe
new-item -type directory -path $folder\$root9\941_British_Isles
new-item -type directory -path $folder\$root9\942_England_and_Wales
new-item -type directory -path $folder\$root9\943_Germany_and_neighboring_central_European_countries
new-item -type directory -path $folder\$root9\944_France_and_Monaco
new-item -type directory -path $folder\$root9\945_Italy_San_Marino_Vatican_City_Malta
new-item -type directory -path $folder\$root9\946_Spain_Andorra_Gibraltar_Portugal
new-item -type directory -path $folder\$root9\947_Russia_and_neighboring_east_European_countries
new-item -type directory -path $folder\$root9\948_Scandinavia
new-item -type directory -path $folder\$root9\949_Other_parts_of_Europe
new-item -type directory -path $folder\$root9\950_History_of_Asia
new-item -type directory -path $folder\$root9\951_China_and_adjacent_areas
new-item -type directory -path $folder\$root9\952_Japan
new-item -type directory -path $folder\$root9\953_Arabian_Peninsula_and_adjacent_areas
new-item -type directory -path $folder\$root9\954_India_and_neighboring_south_Asian_countries
new-item -type directory -path $folder\$root9\955_Iran
new-item -type directory -path $folder\$root9\956_Middle_East_Near_East
new-item -type directory -path $folder\$root9\957_Siberia_Asiatic_Russia
new-item -type directory -path $folder\$root9\958_Central_Asia
new-item -type directory -path $folder\$root9\959_Southeast_Asia
new-item -type directory -path $folder\$root9\960_History_of_Africa
new-item -type directory -path $folder\$root9\961_Tunisia_and_Libya
new-item -type directory -path $folder\$root9\962_Egypt_Sudan_South_Sudan
new-item -type directory -path $folder\$root9\963_Ethiopia_and_Eritrea
new-item -type directory -path $folder\$root9\964_Morocco_Ceuta_Melilla_Western_Sahara_Canary_Islands
new-item -type directory -path $folder\$root9\965_Algeria
new-item -type directory -path $folder\$root9\966_West_Africa_and_offshore_islands
new-item -type directory -path $folder\$root9\967_Central_Africa_and_offshore_islands
new-item -type directory -path $folder\$root9\968_Republic_of_South_Africa_and_neighboring_southern_African_countries
new-item -type directory -path $folder\$root9\969_South_Indian_Ocean_islands
new-item -type directory -path $folder\$root9\970_History_of_North_America
new-item -type directory -path $folder\$root9\971_Canada
new-item -type directory -path $folder\$root9\972_Mexico_Central_America_West_Indies_Bermuda
new-item -type directory -path $folder\$root9\973_United_States
new-item -type directory -path $folder\$root9\974_Northeastern_United_States_New_England_and_Middle_Atlantic_states
new-item -type directory -path $folder\$root9\975_Southeastern_United_States_South_Atlantic_states
new-item -type directory -path $folder\$root9\976_South_central_United_States
new-item -type directory -path $folder\$root9\977_North_central_United_States
new-item -type directory -path $folder\$root9\978_Western_United_States
new-item -type directory -path $folder\$root9\979_Great_Basin_and_Pacific_Slope_region_of_United_States
new-item -type directory -path $folder\$root9\980_History_of_South_America
new-item -type directory -path $folder\$root9\981_Brazil
new-item -type directory -path $folder\$root9\982_Argentina
new-item -type directory -path $folder\$root9\983_Chile
new-item -type directory -path $folder\$root9\984_Bolivia
new-item -type directory -path $folder\$root9\985_Peru
new-item -type directory -path $folder\$root9\986_Colombia_and_Ecuador
new-item -type directory -path $folder\$root9\987_Venezuela
new-item -type directory -path $folder\$root9\988_Guiana
new-item -type directory -path $folder\$root9\989_Paraguay_and_Uruguay
new-item -type directory -path $folder\$root9\990_History_of_other_areas
new-item -type directory -path $folder\$root9\990_History_of_Australasia_Pacific_Ocean_islands_Atlantic_Ocean_islands_Arctic_islands_Antarctica_extraterrestrial_worlds
new-item -type directory -path $folder\$root9\991_992_Not_assigned_or_no_longer_used
new-item -type directory -path $folder\$root9\993_New_Zealand
new-item -type directory -path $folder\$root9\994_Australia
new-item -type directory -path $folder\$root9\995_New_Guinea_and_neighboring_countries_of_Melanesia
new-item -type directory -path $folder\$root9\996_Polynesia_and_other_Pacific_Ocean_islands
new-item -type directory -path $folder\$root9\997_Atlantic_Ocean_islands
new-item -type directory -path $folder\$root9\998_Arctic_islands_and_Antarctica
new-item -type directory -path $folder\$root9\999_Extraterrestrial_worlds
